version: "3.5"

services:

  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=Polus # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    expose:
      - '5432'
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    command: python3 main.py

    restart: unless-stopped

    depends_on:
      - postgres